name: build

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v3
            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - run: yarn install
            - name: Check versions
              run: |
                  yarn --version
                  npx node --version
                  npx ts-node --version
            - run: yarn build
