# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Add issue or pull request to project

on:
  issues:
    types:
      - opened
      - reopened
  # pull_request:
  #   types:
  #     - opened
  #     - reopened

jobs:
  add-to-project:
    name: Add issue or pull request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/scio-labs/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
