version: '3'

services:

  subquery-node:
    image: ronyang/bifrost-subql-node:v0.23.2-alpha.1
    depends_on:
      - "postgres"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./bifrost-subql/:/app
    command:
      - -f=/app
      - --local
