endpoint: wss://mangata-x.api.onfinality.io/public-ws
mock-signature-host: true
block: ${env.MANGATA_BLOCK_NUMBER}
db: ./mangata.db.sqlite

registered-types:
    types:
      ShufflingSeed:
        seed: 'H256'
        proof: 'H512'
      Header:
        parentHash: 'Hash'
        number: 'Compact<BlockNumber>'
        stateRoot: 'Hash'
        extrinsicsRoot: 'Hash'
        digest: 'Digest'
        seed: 'ShufflingSeed'
        count: 'BlockNumber'

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  Tokens:
    Accounts:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: 0
        - free: '1000000000000000000000000' # 1M MG
  Council:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
