// Copyright 2017-2021 @bifrost-finance/api authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@bifrost-finance/api', version: '1.1.51' };
