name: Datadog UI tests

on:
  issue_comment:
    types: [edited]

jobs:
  datadog_ui_test:
    timeout-minutes: 30
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g @datadog/datadog-ci

      - name: Capture Vercel preview URL
        id: vercel_preview_url
        uses: aaron-binary/vercel-preview-url-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: datadog-ci synthetics run-tests
        env:
          SITE_URL: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY:  ${{ secrets.DATADOG_APP_KEY }}
          DATADOG_SITE:  ${{ secrets.DATADOG_SITE }}
