// Copyright 2017-2021 @bifrost-finance/types authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@bifrost-finance/types', version: '1.3.1' };
