// Copyright 2017-2021 @bifrost-finance/type-definitions authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@bifrost-finance/type-definitions', version: '1.1.56' };
