name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          executor/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly-2022-10-30
        components: rustfmt
        target: wasm32-unknown-unknown
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
    - run: yarn --immutable
    - run: yarn check
    - run: yarn build-wasm
    - run: yarn lint
    - run: yarn build
    - run: yarn test
    - name: Test substrate-api-sidecard with chopsticks node
      if: ${{ github.ref_name == 'master' }}
      run: yarn workspace @acala-network/chopsticks-e2e run sidecar
